name: build-class-diagram
on:
    push:
        branches:    
            - master
jobs:
  build-class-diagram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build plug-in
        working-directory: ./es.unican.rivasjm.classd.parent
        run: mvn clean package
      - name: Deploy to personal Github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./es.unican.rivasjm.classd.parent/es.unican.rivasjm.classd.ui.update/target/repository